# Generated by Django 6.0.1 on 2026-01-28 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedRealty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='main.realty')),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_realties', to='main.useraccess')),
            ],
            options={
                'db_table': 'liked_realties',
                'unique_together': {('realty', 'user_access')},
            },
        ),
    ]
